### ISSUE TITLE
Trying to add GW1000 driver and failing with no module named six

### ISSUE THREAD

**Issue by uktricky** [tomdotorg/docker-weewx#10]
Hi, using your v5 Dockerfile to build a new version of WeeWx which works OK

Everything was up and running with the simulator engine but I've now tried to add the GW1000
I've downloaded the gw1000.py and stored this in my docker directory

My run command:
```
docker run \
-d \
-e TZ='Europe/London' \
-v /home/tricky/docker/weewx/weewx.conf:/home/weewx/weewx-data/weewx.conf \
-v /home/tricky/docker/weewx/db:/home/weewx/weewx-data/archive \
-v /home/tricky/docker/webserver/:/home/weewx/weewx-data/public_html/ \
-v /home/tricky/docker/weewx/usrbin/gw1000.py:/home/weewx/weewx-data/bin/user/gw1000.py \
--name weewx \
tricky-weewx:latest
```

My logs show:
```
2024-10-30 17:12:25,675 weewxd[26] INFO __main__: Groups:       weewx
2024-10-30 17:12:25,675 weewxd[26] INFO weewx.engine: Loading station type GW1000 (user.gw1000)
2024-10-30 17:12:25,680 weewxd[26] CRITICAL __main__: Caught unrecoverable exception:
2024-10-30 17:12:25,681 weewxd[26] CRITICAL __main__:     ****  No module named 'six'
2024-10-30 17:12:25,691 weewxd[26] CRITICAL __main__:     ****  Traceback (most recent call last):

2024-10-30 17:12:25,691 weewxd[26] CRITICAL __main__:     ****    File "/home/weewx/weewx/src/weewxd.py", line 121, in main

2024-10-30 17:12:25,691 weewxd[26] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)

2024-10-30 17:12:25,691 weewxd[26] CRITICAL __main__:     ****               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-10-30 17:12:25,691 weewxd[26] CRITICAL __main__:     ****    File "/home/weewx/weewx/src/weewx/engine.py", line 80, in __init__

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****      self.setupStation(config_dict)

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****    File "/home/weewx/weewx/src/weewx/engine.py", line 104, in setupStation

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****      __import__(driver)

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****    File "/home/weewx/weewx-data/bin/user/gw1000.py", line 373, in <module>

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****      import six

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****  ModuleNotFoundError: No module named 'six'

2024-10-30 17:12:25,692 weewxd[26] CRITICAL __main__:     ****  Exiting.
Traceback (most recent call last):
  File "/home/weewx/weewx/src/weewxd.py", line 226, in <module>
    main()
  File "/home/weewx/weewx/src/weewxd.py", line 121, in main
    engine = weewx.engine.StdEngine(config_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weewx/weewx/src/weewx/engine.py", line 80, in __init__
    self.setupStation(config_dict)
  File "/home/weewx/weewx/src/weewx/engine.py", line 104, in setupStation
    __import__(driver)
  File "/home/weewx/weewx-data/bin/user/gw1000.py", line 373, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by uktricky** [comment]
Requires the library installed - Amended the Dockerfile to include:
```

RUN apt-get update \
    &&  apt-get install wget unzip python3 python3-dev python3-pip python3-venv tzdata rsync openssh-client openssl git libffi-dev python3-setuptools libjpeg-dev **python3-six** -y \
    &&  addgroup weewx \
    && useradd -m -g weewx weewx \
```

and also 

```
    && python3 -m pip install paho-mqtt \
    **&& python3 -m pip install six \**
    # If your hardware uses a serial port
    && python3 -m pip install pyserial \
```

**Comment by vinceskahan** [comment]
(not Tom but....) it is reasonable to assume that any docker setup will sometimes require additions if you choose to add things to it, especially drivers.   Not a bug re: this repo in my opinion.
