### ISSUE TITLE
weectl command produces errors

### ISSUE THREAD

**Issue by ervu** [tomdotorg/docker-weewx#7]
Hi,

Tried to run "weectl" command, (login as weewx) but it produces errors "ModuleNotFoundError: No module named 'configobj'"

Did i miss something or are comands changed?
Hope that you can help!

------------------------------------------------------------------

tested workaround: login as root and install the module via command "apt install python3-configobj"

------------------------------------------------------------------
tested with a complete new and clean config
image: "mitct02/weewx:5.1.0-1"

------------------------------------------------------------------

**full error code:**

 cd ../weewx/bin
$ ./weectl
Traceback (most recent call last):
  File "/home/weewx/weewx/bin/./../src/weectl.py", line 75, in <module>
    main()
  File "/home/weewx/weewx/bin/./../src/weectl.py", line 59, in main
    module = importlib.import_module(f'weectllib.{subcommand}_cmd')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/weewx/weewx/src/weectllib/__init__.py", line 9, in <module>
    import weeutil.logger
  File "/home/weewx/weewx/src/weeutil/logger.py", line 13, in <module>
    import configobj
ModuleNotFoundError: No module named 'configobj'
$ ^C
$

**Comment by ervu** [comment]
solved it... Just red the manual and found out that i missed some essential commands up front... Case of RTFM :)

login as weewx or root in bash and run these commands
-source ~/weewx-venv/bin/activate
then the weectl command will run without any errors

source documentation: http://weewx.com/docs/5.1/quickstarts/pip/#customize
